run:
  experiment_name: xgram-smollm2-360m-fineweb10b
  save_root: ./runs

data:
  streaming_data_path:
    - "1"
    - /tmp/xgram-smollm2-fineweb-cache
    - ./data/fineweb_10b_streaming
  streaming_tokenizer_model: /home/bcjiang/.cache/huggingface/hub/models--HuggingFaceTB--SmolLM2-360M/snapshots/f8027fd0eaeea54caa13c31d31b9fdc459c38b49
  streaming_ckpt_path: ./checkpoints/dataloader.ckpt
  use_token_column: tokens
  text_chunk_size: 4096
  prefetch_queue_size: 16
  pack_method: native:truncate

model:
  # SmolLM2-360M 架构 / SmolLM2-360M architecture
  num_layers: 32
  hidden_size: 960
  ffn_hidden_size: 2560
  num_attn_heads: 15
  num_query_groups: 3

training:
  micro_batch_size: 4
  global_batch_size: 512
  train_tokens: 10000000000  # 100 亿 tokens
  lr: 0.0003

evaluation:
  downstream:
    enabled: false
    eval_interval: 400

embedding_injection:
  mode: X-gram
  targets: [v]
  v_layers: [0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9]
  shortconv_enabled: true
  shortconv_kernels: [3, 5, 7]
  hash_enabled: true
  hash_token_map_path: ./assets/token_maps/injection_token_map_smollm2_fineweb_alpha0_5_M32_Cap75968_mc3_mwd0_8.npz
  lambda_init: 1.0
  lambda_warmup_enabled: true
